# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
#   timestamp: 2024-10-01T21:15:08+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Cgroup(Enum):
    host = 'host'
    private = 'private'


class CpuCount(RootModel[int]):
    root: int = Field(..., ge=0)


class CpuPercent(RootModel[int]):
    root: int = Field(..., ge=0, le=100)


class CredentialSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    config: Optional[str] = None
    file: Optional[str] = None
    registry: Optional[str] = None


class Condition(Enum):
    service_started = 'service_started'
    service_healthy = 'service_healthy'
    service_completed_successfully = 'service_completed_successfully'


class DependsOn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    restart: Optional[Union[bool, str]] = None
    required: Optional[bool] = True
    condition: Condition


class Devices(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str
    target: Optional[str] = None
    permissions: Optional[str] = None


class Extends(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: str
    file: Optional[str] = None


class Logging(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    driver: Optional[str] = None
    options: Optional[Dict[str, Optional[Union[str, float]]]] = None


class OomScoreAdj(RootModel[int]):
    root: int = Field(..., ge=-1000, le=1000)


class Ports(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    mode: Optional[str] = None
    host_ip: Optional[str] = None
    target: Optional[Union[int, str]] = None
    published: Optional[Union[str, int]] = None
    protocol: Optional[str] = None
    app_protocol: Optional[str] = None


class PullPolicy(Enum):
    always = 'always'
    never = 'never'
    if_not_present = 'if_not_present'
    build = 'build'
    missing = 'missing'


class Selinux(Enum):
    z = 'z'
    z_1 = 'Z'


class Bind(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    propagation: Optional[str] = None
    create_host_path: Optional[Union[bool, str]] = None
    selinux: Optional[Selinux] = None


class Volume1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nocopy: Optional[Union[bool, str]] = None
    subpath: Optional[str] = None


class Size(RootModel[int]):
    root: int = Field(..., ge=0)


class Tmpfs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    size: Optional[Union[Size, str]] = None
    mode: Optional[Union[float, str]] = None


class Volumes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str
    source: Optional[str] = None
    target: Optional[str] = None
    read_only: Optional[Union[bool, str]] = None
    consistency: Optional[str] = None
    bind: Optional[Bind] = None
    volume: Optional[Volume1] = None
    tmpfs: Optional[Tmpfs] = None


class Healthcheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    disable: Optional[Union[bool, str]] = None
    interval: Optional[str] = None
    retries: Optional[Union[float, str]] = None
    test: Optional[Union[str, List[str]]] = None
    timeout: Optional[str] = None
    start_period: Optional[str] = None
    start_interval: Optional[str] = None


class Action(Enum):
    rebuild = 'rebuild'
    sync = 'sync'
    sync_restart = 'sync+restart'


class WatchItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ignore: Optional[List[str]] = None
    path: str
    action: Action
    target: Optional[str] = None


class Development(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    watch: Optional[List[WatchItem]] = None


class Order(Enum):
    start_first = 'start-first'
    stop_first = 'stop-first'


class RollbackConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parallelism: Optional[Union[int, str]] = None
    delay: Optional[str] = None
    failure_action: Optional[str] = None
    monitor: Optional[str] = None
    max_failure_ratio: Optional[Union[float, str]] = None
    order: Optional[Order] = None


class UpdateConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parallelism: Optional[Union[int, str]] = None
    delay: Optional[str] = None
    failure_action: Optional[str] = None
    monitor: Optional[str] = None
    max_failure_ratio: Optional[Union[float, str]] = None
    order: Optional[Order] = None


class Limits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpus: Optional[Union[float, str]] = None
    memory: Optional[str] = None
    pids: Optional[Union[int, str]] = None


class RestartPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    condition: Optional[str] = None
    delay: Optional[str] = None
    max_attempts: Optional[Union[int, str]] = None
    window: Optional[str] = None


class Preference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    spread: Optional[str] = None


class Placement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    constraints: Optional[List[str]] = None
    preferences: Optional[List[Preference]] = None
    max_replicas_per_node: Optional[Union[int, str]] = None


class DiscreteResourceSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Optional[str] = None
    value: Optional[Union[float, str]] = None


class GenericResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    discrete_resource_spec: Optional[DiscreteResourceSpec] = None


class ConfigItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subnet: Optional[str] = None
    ip_range: Optional[str] = None
    gateway: Optional[str] = None
    aux_addresses: Optional[Dict[str, str]] = None


class Ipam(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    driver: Optional[str] = None
    config: Optional[List[ConfigItem]] = None
    options: Optional[Dict[str, str]] = None


class External(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None


class External2(BaseModel):
    name: Optional[str] = None


class EnvFile1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    required: Optional[Union[bool, str]] = True


class ListOfStrings(RootModel[List[str]]):
    root: List[str]


class ListOrDict1(RootModel[List[str]]):
    root: List[str]


class ExtraHosts1(RootModel[List[str]]):
    root: List[str]


class BlkioLimit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Optional[str] = None
    rate: Optional[Union[int, str]] = None


class BlkioWeight(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Optional[str] = None
    weight: Optional[Union[int, str]] = None


class ServiceConfigOrSecret1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Optional[str] = None
    target: Optional[str] = None
    uid: Optional[str] = None
    gid: Optional[str] = None
    mode: Optional[Union[float, str]] = None


class Ulimits1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hard: Union[int, str]
    soft: Union[int, str]


class Constraints(RootModel[Any]):
    root: Any


class Build(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context: Optional[str] = None
    dockerfile: Optional[str] = None
    dockerfile_inline: Optional[str] = None
    entitlements: Optional[List[str]] = None
    args: Optional[Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]] = (
        None
    )
    ssh: Optional[Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]] = (
        None
    )
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    cache_from: Optional[List[str]] = None
    cache_to: Optional[List[str]] = None
    no_cache: Optional[Union[bool, str]] = None
    additional_contexts: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    network: Optional[str] = None
    pull: Optional[Union[bool, str]] = None
    target: Optional[str] = None
    shm_size: Optional[Union[int, str]] = None
    extra_hosts: Optional[Union[Dict[str, Union[str, List[Any]]], ExtraHosts1]] = None
    isolation: Optional[str] = None
    privileged: Optional[Union[bool, str]] = None
    secrets: Optional[List[Union[str, ServiceConfigOrSecret1]]] = None
    tags: Optional[List[str]] = None
    ulimits: Optional[Dict[str, Union[Union[int, str], Ulimits1]]] = None
    platforms: Optional[List[str]] = None


class BlkioConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    device_read_bps: Optional[List[BlkioLimit]] = None
    device_read_iops: Optional[List[BlkioLimit]] = None
    device_write_bps: Optional[List[BlkioLimit]] = None
    device_write_iops: Optional[List[BlkioLimit]] = None
    weight: Optional[Union[int, str]] = None
    weight_device: Optional[List[BlkioWeight]] = None


class Networks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aliases: Optional[List[str]] = None
    ipv4_address: Optional[str] = None
    ipv6_address: Optional[str] = None
    link_local_ips: Optional[List[str]] = None
    mac_address: Optional[str] = None
    driver_opts: Optional[Dict[str, Union[str, float]]] = None
    priority: Optional[float] = None


class Device(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: Optional[List[str]] = None
    count: Optional[Union[str, int]] = None
    device_ids: Optional[List[str]] = None
    driver: Optional[str] = None
    options: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None


class Network(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    driver: Optional[str] = None
    driver_opts: Optional[Dict[str, Union[str, float]]] = None
    ipam: Optional[Ipam] = None
    external: Optional[External] = None
    internal: Optional[Union[bool, str]] = None
    enable_ipv6: Optional[Union[bool, str]] = None
    attachable: Optional[Union[bool, str]] = None
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None


class Volume(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    driver: Optional[str] = None
    driver_opts: Optional[Dict[str, Union[str, float]]] = None
    external: Optional[External] = None
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None


class Secret(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    environment: Optional[str] = None
    file: Optional[str] = None
    external: Optional[External2] = None
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    driver: Optional[str] = None
    driver_opts: Optional[Dict[str, Union[str, float]]] = None
    template_driver: Optional[str] = None


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    content: Optional[str] = None
    environment: Optional[str] = None
    file: Optional[str] = None
    external: Optional[External2] = None
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    template_driver: Optional[str] = None


class Reservations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpus: Optional[Union[float, str]] = None
    memory: Optional[str] = None
    generic_resources: Optional[List[GenericResource]] = None
    devices: Optional[List[Device]] = None


class Resources(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limits: Optional[Limits] = None
    reservations: Optional[Reservations] = None


class Deployment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Optional[str] = None
    endpoint_mode: Optional[str] = None
    replicas: Optional[Union[int, str]] = None
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    rollback_config: Optional[RollbackConfig] = None
    update_config: Optional[UpdateConfig] = None
    resources: Optional[Resources] = None
    restart_policy: Optional[RestartPolicy] = None
    placement: Optional[Placement] = None


class Include1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Optional[Union[str, ListOfStrings]] = None
    env_file: Optional[Union[str, ListOfStrings]] = None
    project_directory: Optional[str] = None


class Service(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    develop: Optional[Development] = None
    deploy: Optional[Deployment] = None
    annotations: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    attach: Optional[Union[bool, str]] = None
    build: Optional[Union[str, Build]] = None
    blkio_config: Optional[BlkioConfig] = None
    cap_add: Optional[List[str]] = None
    cap_drop: Optional[List[str]] = None
    cgroup: Optional[Cgroup] = None
    cgroup_parent: Optional[str] = None
    command: Optional[Union[str, List[str]]] = None
    configs: Optional[List[Union[str, ServiceConfigOrSecret1]]] = None
    container_name: Optional[str] = None
    cpu_count: Optional[Union[str, CpuCount]] = None
    cpu_percent: Optional[Union[str, CpuPercent]] = None
    cpu_shares: Optional[Union[float, str]] = None
    cpu_quota: Optional[Union[float, str]] = None
    cpu_period: Optional[Union[float, str]] = None
    cpu_rt_period: Optional[Union[float, str]] = None
    cpu_rt_runtime: Optional[Union[float, str]] = None
    cpus: Optional[Union[float, str]] = None
    cpuset: Optional[str] = None
    credential_spec: Optional[CredentialSpec] = None
    depends_on: Optional[Union[ListOfStrings, Dict[str, DependsOn]]] = None
    device_cgroup_rules: Optional[List[str]] = None
    devices: Optional[List[Union[str, Devices]]] = None
    dns: Optional[Union[str, ListOfStrings]] = None
    dns_opt: Optional[List[str]] = None
    dns_search: Optional[Union[str, ListOfStrings]] = None
    domainname: Optional[str] = None
    entrypoint: Optional[Union[str, List[str]]] = None
    env_file: Optional[Union[str, List[Union[str, EnvFile1]]]] = None
    environment: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    expose: Optional[List[Union[str, float]]] = None
    extends: Optional[Union[str, Extends]] = None
    external_links: Optional[List[str]] = None
    extra_hosts: Optional[Union[Dict[str, Union[str, List[Any]]], ExtraHosts1]] = None
    group_add: Optional[List[Union[str, float]]] = None
    healthcheck: Optional[Healthcheck] = None
    hostname: Optional[str] = None
    image: Optional[str] = None
    init: Optional[Union[bool, str]] = None
    ipc: Optional[str] = None
    isolation: Optional[str] = None
    labels: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    links: Optional[List[str]] = None
    logging: Optional[Logging] = None
    mac_address: Optional[str] = None
    mem_limit: Optional[Union[float, str]] = None
    mem_reservation: Optional[Union[str, int]] = None
    mem_swappiness: Optional[Union[int, str]] = None
    memswap_limit: Optional[Union[float, str]] = None
    network_mode: Optional[str] = None
    networks: Optional[Union[ListOfStrings, Dict[str, Optional[Networks]]]] = None
    oom_kill_disable: Optional[Union[bool, str]] = None
    oom_score_adj: Optional[Union[str, OomScoreAdj]] = None
    pid: Optional[str] = None
    pids_limit: Optional[Union[float, str]] = None
    platform: Optional[str] = None
    ports: Optional[List[Union[float, str, Ports]]] = None
    privileged: Optional[Union[bool, str]] = None
    profiles: Optional[List[str]] = None
    pull_policy: Optional[PullPolicy] = None
    read_only: Optional[Union[bool, str]] = None
    restart: Optional[str] = None
    runtime: Optional[str] = None
    scale: Optional[Union[int, str]] = None
    security_opt: Optional[List[str]] = None
    shm_size: Optional[Union[float, str]] = None
    secrets: Optional[List[Union[str, ServiceConfigOrSecret1]]] = None
    sysctls: Optional[
        Union[Dict[str, Optional[Union[str, float, bool]]], ListOrDict1]
    ] = None
    stdin_open: Optional[Union[bool, str]] = None
    stop_grace_period: Optional[str] = None
    stop_signal: Optional[str] = None
    storage_opt: Optional[Dict[str, Any]] = None
    tmpfs: Optional[Union[str, ListOfStrings]] = None
    tty: Optional[Union[bool, str]] = None
    ulimits: Optional[Dict[str, Union[Union[int, str], Ulimits1]]] = None
    user: Optional[str] = None
    uts: Optional[str] = None
    userns_mode: Optional[str] = None
    volumes: Optional[List[Union[str, Volumes]]] = None
    volumes_from: Optional[List[str]] = None
    working_dir: Optional[str] = None


class ComposeSpecification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Optional[str] = Field(
        None, description='declared for backward compatibility, ignored.'
    )
    name: Optional[str] = Field(
        None,
        description='define the Compose project name, until user defines one explicitly.',
    )
    include: Optional[List[Union[str, Include1]]] = Field(
        None, description='compose sub-projects to be included.'
    )
    services: Optional[Dict[str, Service]] = None
    networks: Optional[Dict[str, Optional[Network]]] = None
    volumes: Optional[Dict[str, Optional[Volume]]] = None
    secrets: Optional[Dict[str, Secret]] = None
    configs: Optional[Dict[str, Config]] = None
