# Where to write backups to
backup_folder = "./backups"

# A list of any docker-compose files that should be excluded from backup
docker_compose_exclusions = []

# A list of regexes that can be matched for any volumes that should be excluded from backup.
volume_exclusions = [
    '/etc/passwd',
    '/etc/groups',
    '/etc/localtime',
    '/var/run/docker.sock',
    '/etc/os-release',
    '/proc',
    '/sys',
]

# A list of regexes that, if matched, will force a volume to be included, even if it would otherwise be
# excluded via the exclusions list above.
volume_inclusions = []

# Number of backups to keep
number_backups = 2
