# A TOML list containing any volumes that should be excluded from backup.
# Note that these are matched to the start of any volume entry, so any volume that starts with any of the entries
# in this list are excluded.
exclusions = [
    '/etc/passwd',
    '/etc/groups',
    '/etc/localtime',
    '/var/run/docker.sock',
    '/etc/os-release',
]
